### ISSUE TITLE
Missing File and Function 'blkproc'

### ISSUE THREAD

**Issue by TobiVanHelsinki** [v12/online-fingerprint-verification-sdk#1]
Hey, i wanted to use your code for my thesis, but the file blkproc seems missing.

called from:
error: 'blkproc' undefined near line 53 column 16
error: called from
    ridgesegment at line 53 column 14
    extractminutae at line 24 column 16
    engine at line 11 column 11

It would be nice if someone could include this.

**Comment by v12** [comment]
@TobiVanHelsinki the project was automatically exported from Google Code before it closed and the original code was not written by myself and I kept a copy of the repo for my personal reference without ever actually running it, sorry.

Would be great if you share your results when you get it working (if at all, of course). Thanks!

**Comment by TobiVanHelsinki** [comment]
Hi,

I got it working. The thing is, that I only have Ocatave, not Matlab. So I needed to adjust many parts to be multiplatform compatible. Also I had to install some more packages.
Shall I share the new code?

**Comment by v12** [comment]
@TobiVanHelsinki oh, absolutely, if you're happy to do this, that'd be great! Sharing is caring 😉
